Repository nus-ncl/CTFPro, pull requests merged in 2021-12, with the labels that each got.

#7 Updates on the apiServer.py
  api/README.md
  api/apiServer.py
Labels: enhancement, back-end

#19 [Backend] Create Installation Script
  api/scripts/install_req.sh
Labels: enhancement, back-end

#21 Create fastapi.yml
  .github/workflows/fastapi.yml
Labels: enhancement, ci/cd

#20 [Backend] Create test folder and test.py
  api/tests/test.py
Labels: back-end

#22 [CI/CD] Fix test unit and Github action for Backend
  .github/workflows/fastapi.yml
  api/scripts/install_req.sh
  api/tests/test.py
Labels: ci/cd, back-end

#15 Initial front end with database integration
  web/README.md
  web/nclsite/settings.py
  web/vms/forms.py
  web/vms/migrations/0005_auto_20211208_2033.py
  web/vms/migrations/0006_auto_20211224_1337.py
  web/vms/migrations/0007_auto_20211224_1342.py
  web/vms/migrations/0008_delete_authuser.py
  web/vms/models.py
  web/vms/templates/vms/challenges.html
  web/vms/templates/vms/component-form.html
  web/vms/templates/vms/components.html
  web/vms/templates/vms/dashboard.html
  web/vms/templates/vms/index.html
  web/vms/templates/vms/landpage.html
  web/vms/templates/vms/monitor.html
  web/vms/templates/vms/register.html
  web/vms/templates/vms/stats.html
  web/vms/urls.py
  web/vms/views.py
Labels: enhancement, front-end

#16 Database
  ctfpro_dump.sql
  db/README.md
Labels: enhancement, database

#18 Vagrant file
  api/config/Vagrantfile
  api/config/aws/vagrantFile
  api/config/vb/vagrantFile
Labels: enhancement, back-end
